# Generated by Django 4.1 on 2022-08-15 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('comments', models.ManyToManyField(blank=True, related_name='bids', to='auctions.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SP', 'Sport'), ('Fd', 'Food'), ('T', 'Toys'), ('Off', 'Office'), ('CE', 'Computer and Electronics'), ('Fu', 'Furniture'), ('HPC', 'Health and Personal Care'), ('BMV', 'Books/Music/Video'), ('O', 'Other')], max_length=3)),
                ('bids', models.ManyToManyField(blank=True, related_name='auctions', to='auctions.bids')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_prices', to='auctions.bids')),
            ],
        ),
    ]
