# Generated by Django 4.1 on 2022-09-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist_user_watchlist_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='comments',
        ),
        migrations.AddField(
            model_name='auction',
            name='bids',
            field=models.ManyToManyField(blank=True, to='auctions.bids'),
        ),
    ]
