# Generated by Django 4.1 on 2022-09-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bids_comments_auction_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bids',
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(null=True),
        ),
    ]
