# Generated by Django 4.1 on 2022-09-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_bids_auction_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
